/* Datos de demostración usados por el panel de administración.
 * Los importes de productos en pedidos son subtotales de línea y no cambian
 * cuando se edita el catálogo.
 */
window.OpalinaAdminDatos = {
  pedidos: {
    "OP-2026-0052": {
      cliente: "María López",
      email: "maria.lopez@correo.com",
      telefono: "+51 999 888 777",
      desde: "enero 2024",
      pedidos: 12,
      modalidad: "Delivery a domicilio",
      direccion: "Av. Grau 123, Urb. San Eduardo, Piura",
      referencia: "Casa de 2 pisos, portón gris",
      fecha: "29 de agosto, 2026 · 10:00 AM",
      notas: "Por favor llamar al llegar.",
      total: 260,
      estado: "pendiente",
      productos: [
        {
          id: "6-JardinOpalinaGrande",
          nombre: "Jardín de Opalina Grande",
          categoria: "Premium",
          cantidad: 1,
          precio: 150,
        },
        {
          id: "12-RamoOpalinaMorado",
          nombre: "Ramo Opalina Morado",
          categoria: "Romántico",
          cantidad: 2,
          precio: 110,
        },
      ],
    },
    "OP-2026-0049": {
      cliente: "Carlos Ramírez",
      email: "",
      telefono: "+51 987 654 321",
      desde: "",
      pedidos: 0,
      modalidad: "",
      direccion: "",
      referencia: "",
      fecha: "",
      notas: "",
      total: 180,
      estado: "pendiente",
      productos: [
        {
          id: "3-Buchon12Rosas",
          nombre: "Buchón 12 Rosas",
          categoria: "Romántico",
          cantidad: 1,
          precio: 85,
        },
        {
          id: "2-BoxFloralConChocolates",
          nombre: "Box Floral con Chocolates",
          categoria: "Cumpleaños",
          cantidad: 1,
          precio: 95,
        },
      ],
    },
    "OP-2026-0048": {
      cliente: "María López",
      email: "maria.lopez@correo.com",
      telefono: "+51 999 888 777",
      desde: "enero 2024",
      pedidos: 12,
      modalidad: "",
      direccion: "",
      referencia: "",
      fecha: "",
      notas: "",
      total: 150,
      estado: "proceso",
      productos: [
        {
          id: "6-JardinOpalinaGrande",
          nombre: "Jardín de Opalina Grande",
          categoria: "Premium",
          cantidad: 1,
          precio: 150,
        },
      ],
    },
    "OP-2026-0045": {
      cliente: "Ana Torres",
      email: "",
      telefono: "+51 912 345 678",
      desde: "",
      pedidos: 0,
      modalidad: "",
      direccion: "",
      referencia: "",
      fecha: "",
      notas: "",
      total: 280,
      estado: "proceso",
      productos: [
        {
          id: "4-CoronaPremium",
          nombre: "Corona Premium",
          categoria: "Condolencias",
          cantidad: 1,
          precio: 280,
        },
      ],
    },
    "OP-2026-0041": {
      cliente: "Luis Fernández",
      email: "",
      telefono: "+51 955 667 788",
      desde: "",
      pedidos: 0,
      modalidad: "",
      direccion: "",
      referencia: "",
      fecha: "",
      notas: "",
      total: 162,
      estado: "entregado",
      productos: [
        {
          id: "9-RamoAmarillo21Marzo",
          nombre: "Ramo Amarillo 21 de Marzo",
          categoria: "Temporada",
          cantidad: 2,
          precio: 130,
        },
        {
          id: "5-DuoBobaFlor",
          nombre: "Dúo Boba + Flor",
          categoria: "Temporada",
          cantidad: 1,
          precio: 32,
        },
      ],
    },
  },
  productos: {
    "8-MiniRamoCotidiano": {
      nombre: "Mini Ramo Cotidiano",
      categoria: "Temporada",
      precio: 22,
      stock: 18,
      disponible: true,
      descripcion:
        "1-3 tallos con follaje y tarjeta corta para detalles de oficina.",
      sku: "OPA-001",
      destacado: false,
    },
    "12-RamoOpalinaMorado": {
      nombre: "Ramo Opalina Morado",
      categoria: "Romántico",
      precio: 55,
      stock: 28,
      disponible: true,
      descripcion: "Gerberas, hortensias y margaritas en paleta lila/morado.",
      sku: "OPA-002",
      destacado: false,
    },
    "9-RamoAmarillo21Marzo": {
      nombre: "Ramo Amarillo 21 de Marzo",
      categoria: "Temporada",
      precio: 65,
      stock: 12,
      disponible: true,
      descripcion:
        "Girasoles y flores amarillas de tendencia con lazo amarillo.",
      sku: "OPA-003",
      destacado: false,
    },
    "3-Buchon12Rosas": {
      nombre: "Buchón 12 Rosas",
      categoria: "Romántico",
      precio: 85,
      stock: 7,
      disponible: true,
      descripcion: "Bouquet grande con 12 rosas en papel coreano rojo/negro.",
      sku: "OPA-004",
      destacado: false,
    },
    "2-BoxFloralConChocolates": {
      nombre: "Box Floral con Chocolates",
      categoria: "Cumpleaños",
      precio: 95,
      stock: 9,
      disponible: true,
      descripcion: "Ramo corto en box cilíndrica con rosas y chocolatitos.",
      sku: "OPA-005",
      destacado: false,
    },
    "11-RamoLiriosPremium": {
      nombre: "Ramo de Lirios Premium",
      categoria: "Premium",
      precio: 110,
      stock: 4,
      disponible: true,
      descripcion: "Lirios claros con flores de apoyo y follaje fresco.",
      sku: "OPA-006",
      destacado: false,
    },
    "6-JardinOpalinaGrande": {
      nombre: "Jardín de Opalina Grande",
      categoria: "Premium",
      precio: 150,
      stock: 3,
      disponible: true,
      descripcion: "Bouquet firma grande, multivarietal con tarjeta impresa.",
      sku: "OPA-007",
      destacado: false,
    },
    "10-RamoGraduación": {
      nombre: "Ramo de Graduación",
      categoria: "Cumpleaños",
      precio: 78,
      stock: 15,
      disponible: true,
      descripcion: "Rosas o gerberas con lazo y mini topper personalizable.",
      sku: "OPA-008",
      destacado: false,
    },
    "7-LagrimaCondolencias": {
      nombre: "Lágrima Condolencias",
      categoria: "Condolencias",
      precio: 120,
      stock: 6,
      disponible: true,
      descripcion: "Arreglo sobrio de condolencia estandarizado con faja.",
      sku: "OPA-009",
      destacado: false,
    },
    "4-CoronaPremium": {
      nombre: "Corona Premium",
      categoria: "Condolencias",
      precio: 280,
      stock: 0,
      disponible: true,
      descripcion: "Corona o parante ceremonial con flores mixtas y mensaje.",
      sku: "OPA-010",
      destacado: false,
    },
    "5-DuoBobaFlor": {
      nombre: "Dúo Boba + Flor",
      categoria: "Temporada",
      precio: 32,
      stock: 22,
      disponible: true,
      descripcion: "Colaborativo con Boba Pop. Sleeve pequeño con tarjeta.",
      sku: "OPA-011",
      destacado: false,
    },
    "1-arregloPersonalizado": {
      nombre: "Arreglo Personalizado",
      categoria: "Personalizado",
      precio: 120,
      stock: 11,
      disponible: true,
      descripcion: "Diseño según ocasión, colores preferidos y presupuesto.",
      sku: "OPA-012",
      destacado: false,
    },
  },
};
